
on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: x86_64
          - os: ubuntu-latest
            arch: x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install aqtinstall
        run: pip install aqtinstall
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.1'
          cache: 'true'
          setup-python: false
          extra: '--base http://mirrors.ocf.berkeley.edu/qt/'
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install wheel build tools
        run: pip install build py-build-cmake ninja pyside6 shiboken6 shiboken6-generator
      # - name: Build wheels
      #   run: python -m build --no-isolation --wheel
      #   uses: pypa/cibuildwheel@v2.19.1
